export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER';
export const CREATE_BUCKET_LIST = 'CREATE_BUCKET_LIST';
export const FETCH_BUCKET_LIST = 'FETCH_BUCKET_LIST';
export const FETCH_A_BUCKET_LIST_ITEMS = 'FETCH_A_BUCKET_LIST_ITEMS';
export const EDIT_A_BUCKET_LIST = 'EDIT_A_BUCKET_LIST';
export const CREATE_BUCKET_ITEM = 'CREATE_BUCKET_ITEM';
export const EDIT_A_BUCKET_ITEM = 'EDIT_A_BUCKET_ITEM';
